[build]
  command = "npm run build"
  publish = "dist"               

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"


[build.environment]
  NODE_VERSION = "20"

# Ensure all routes go through the SSR function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
