[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

# Tell Netlify to render all routes with the Nuxt SSR system function
[[headers]]
  for = "/*"
  [headers.values]
  X-NF-Render-Mode = "ssr"
