# netlify.toml
[build]
  command = "npm run build"
  publish = ".output/public"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "20"

# (safety) If Netlify ever misses Nitro's generated redirect,
# this ensures all routes go to the SSR function.
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
